source "https://rubygems.org"

ruby "3.1.0"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
end

group :development do
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
end


gem "devise", "~> 4.9"
gem 'rack-cors'
gem 'devise-jwt'
gem 'jsonapi-serializer'
gem 'dotenv-rails'